config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }\

  get "users/:id", to: "users#show", constraints: { id: /\d+/ }, as: "user"
  get "users/:nickname", to: "users#show", constraints: { nickname: /\w+/ }, as: "nickname"
  resources :users, only: [ :edit, :update ] do
    member do
      delete :remove_avatar

      post :follow, to: "subscriptions#create"
      delete :unfollow, to: "subscriptions#destroy"
    end

    collection do
      get "profile/new", action: :new_profile, as: "new_profile"
      post "profile/create", action: :create_profile, as: "create_profile"
    end
  end

  resources :posts, except: [ :index ]  do
    post :like, to: "likes#create", as: :like
    delete :like, to: "likes#destroy", as: :unlike

    resources :comments, shallow: true do
      post :like, to: "likes#create", as: :like
      delete :like, to: "likes#destroy", as: :unlike
      get :replies
    end
  end
  get "/:feed", to: "posts#feed", as: :feed, constraints: { feed: /(hot|new|subscriptions|best)/ }

  root to: redirect("/hot")

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likable

  belongs_to :user
  belongs_to :post, counter_cache: true

  has_many :replies, class_name: "Comment", foreign_key: :replied_to_id, dependent: :destroy
  belongs_to :replied_to, class_name: "Comment", optional: true, counter_cache: :replies_count

  validates :body, length: { minimum: 3, maximum: 200 }
  validate :replied_to_a_comment_on_the_same_post, if: :is_reply?
  validate :replied_to_not_a_reply, if: :is_reply?

  before_save :strip_body

  scope :not_replies, -> { where(replied_to: nil) }
  scope :replying_to, ->(comment) { where(replied_to: comment) }

  paginates_per 10

  def is_reply?
    replied_to_id.present?
  end

  private

  def replied_to_a_comment_on_the_same_post
    unless replied_to.post_id == post_id
      errors.add(:body, "replies to the comment from another post")
    end
  end

  def replied_to_not_a_reply
    if replied_to.replied_to
      errors.add(:body, "can't reply to a reply")
    end
  end

  def strip_body
    self.body = body.strip
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment_and_post, only: %i[ show edit update destroy ]
  before_action :authorize_comment, only: %i[ show edit update destroy ]

  def index
    page = params[:page]
    @order = params[:order]
    @post_id = params[:post_id]

    @comments = Post.find(@post_id)
                    .comments.not_replies
                    .with_user_like(current_user)
                    .includes(user: :avatar_attachment)
                    .page(page)

    if user_signed_in?
      @comments = @comments.includes(preview_likes: [ user: [ :avatar_attachment ] ])
    end

    if @order == "older"
      @comments = @comments.order(created_at: :asc)
    elsif @order == "newer"
      @comments = @comments.order(created_at: :desc)
    else
      @order = "rating"
      @comments = @comments.order(likes_count: :desc, created_at: :desc)
    end

    render :index, formats: @comments.first_page? ? :html : :turbo_stream
  end

  def replies
    @comment_id = params[:comment_id]

    if params[:hide]
      @hide = true
    else
      page = params[:page]
      comment = Comment.find(params[:comment_id])
      @replies = Comment.replying_to(comment)
                        .with_user_like(current_user)
                        .includes(user: :avatar_attachment)
                        .page(page).per(5)

      if user_signed_in?
        @replies = @replies.includes(preview_likes: [ user: [ :avatar_attachment ] ])
      end
    end

    render :replies, formats: :turbo_stream
  end

  def show
    @preview_likes = @comment.preview_likes.includes(user: [ :avatar_attachment ])
    render @comment
  end

  def new
    authorize Comment

    if params[:reply_nickname]
      body = "#{params[:reply_nickname]}, "
    end

    @ref_reply_id = params[:ref_reply_id]
    @comment ||= Comment.new(post_id: params.expect(:post_id),
                             replied_to_id: params[:replied_to_id],
                             body: body,)
    render :new, layout: false
  end

  def edit
    @previous_page = @post
    render :edit, layout: false
  end

  def create
    authorize Comment

    @comment = Comment.new(comment_params)
    @comment.user = current_user
    form_frame_id = request.headers["Turbo-Frame"]

    respond_to do |format|
      if @comment.save
        notice = "Comment has been added."
        replied_to_id = @comment.replied_to_id

        if turbo_frame_request?
          format.turbo_stream do
            render :create, locals: { notice: notice,
                                      replied_to_id: replied_to_id,
                                      form_frame_id: form_frame_id }
          end
        else
          format.html { redirect_to post_path(@comment.post, corder: "newer"), notice: notice }
        end

        format.json { render :show, status: :created, location: @comment }
      else
        if turbo_frame_request?
          @ref_reply_id = form_frame_id[/comment_(\d+)_new/, 1]
        end

        format.html { render :new, status: :unprocessable_entity, layout: !turbo_frame_request? }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    previous_update = @comment.updated_at
    respond_to do |format|
      if @comment.update(comment_params)
        current_update = @comment.updated_at
        is_changed = previous_update != current_update
        notice = is_changed ? "Comment has been updated." : nil
        frame_id = request.headers["Turbo-Frame"]

        format.json { render :show, status: :ok, location: @comment }
        format.any { render :update, formats: :turbo_stream,
                            locals: { notice: notice, frame_id: frame_id }  }
      else
        @previous_page = @post
        format.html { render :edit, status: :unprocessable_entity, layout: !turbo_frame_request? }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy!

    respond_to do |format|
      notice = "Comment has been deleted."
      frame_id = request.headers["Turbo-Frame"]
      format.json { head :no_content }
      format.any { render :destroy, formats: :turbo_stream,
                          locals: { notice: notice, frame_id: frame_id } }
    end
  end

  private

  def set_comment_and_post
    @comment = Comment.find(params.expect(:id))
    @post = Post.find(params[:post_id]) if params[:post_id]
  end

  def authorize_comment
    authorize @comment
  end

  def comment_params
    params.expect(comment: [ :body, :post_id, :replied_to_id ])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def format_comment_date(date)
        date.in_time_zone("Warsaw").strftime("%F %T")
    end

    def modified?(comment)
        comment.created_at != comment.updated_at
    end

    def ats_to_links(body)
        body.gsub(/(?<=p>)@(\w+)(?=,)/) do
            link_to($~, nickname_path($1),
                    class: "link-underline link-underline-opacity-0 text-danger",
                    data: { turbo_frame: "_top" })
        end.html_safe
    end
end

app/views/comments/_comment.html.erb
<turbo-frame id="<%= dom_id comment %>_frame"
              data-controller="turbo-frame"
              data-turbo-frame-preserve-height-value=true
              data-turbo-frame-target='spinner'
>
  <div class="card overflow-hidden comment-block border-0">
    <div class="card-header d-flex py-0 border-0 bg-white">
      <div class="col-10 d-flex align-items-center text-truncate">
        <div class="comment-avatar me-2">
          <%= avatar comment.user, class_name: 'img-xs rounded-circle' %>
        </div>
        <div class="fw-semibold text-truncate">
          <%= link_to nickname(comment.user), comment.user,
            class: "nav-link text-truncate",
            title: nickname(comment.user),
            data: { turbo_frame: "_top" }
          %>
        </div>
        <span class="text-secondary mx-2">
          •
        </span>
        <small class="text-body-secondary" role="button" title="<%= comment.created_at %>">
          <%= time_ago_in_words comment.created_at %> ago
        </small>
        <% if modified?(comment) %>
          <sup class="text-body-tertiary opacity-50 ms-2 top-0">edited</sup>
        <% end %>
      </div>
      <div class="col-2 text-end">
        <% if comment.user == current_user %>
          <div class="comment-controls text-secondary">
            <div class="d-inline me-2">
              <%= link_to edit_comment_path(comment),
                class: "nav-link edit-comment d-inline",
                title: "Edit",
                data: {
                    turbo_frame: "#{dom_id comment}_frame"
                } do
              %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
            </div>
            <%= link_to comment_path(comment),
              class: "nav-link d-inline",
              title: "Delete",
              data: {
                turbo_method: :delete,
                action: "click->turbo-frame#replaceBySpinner"
              } do
            %>
              <i class="bi bi-trash3"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="card-body py-2 position-relative"
         data-controller='read-more' data-read-more-max-height-value=200>
      <div class="comment-body" data-read-more-target="textToHide">
        <%= ats_to_links(simple_format(comment.body)) %>
      </div>
      <div class="position-relative" data-read-more-target="showMoreButton" hidden>
        <div class="comment-show-more-fade position-absolute w-100 bottom-100"></div>
        <button class="show-more-btn nav-link text-secondary fw-medium"
                data-action='click->read-more#showMore'>
          <small>More ...</small>
        </button>
      </div>
    </div>
    <div class="card-footer text-body-secondary border-0 bg-white pt-1">
      <div class="d-inline-block me-3">
        <%= render 'shared/like', resource: comment %>
      </div>
      <% unless comment.is_reply? %>
        <div class="replies-count d-inline-block me-3">
          <i class="bi bi-reply-fill"></i>
          <%= comment.replies_count %>
        </div>
      <% end %>
      <div class="d-inline-block">
        <small>
          <%= link_to "Reply",
                      new_post_comment_path(post_id: comment.post_id,
                                            replied_to_id: comment.replied_to_id || comment.id,
                                            ref_reply_id: comment.id,
                                            reply_nickname: nickname(comment.user)),
                      class: 'nav-link text-secondary fw-medium',
                      data: { turbo_frame: "#{dom_id comment}_new_reply_frame" }
          %>
        </small>
      </div>
    </div>
    <%= render partial: 'comments/new_reply', locals: { frame_id: "#{dom_id comment}_new_reply_frame" }  %>
    <% unless comment.is_reply? %>
      <div class="ps-3 pb-2">
        <% if comment.replies.any? %>
          <turbo-frame id="<%= dom_id comment %>_replies_frame"
            data-controller="turbo-frame"
            data-turbo-frame-target='content'
            data-turbo-frame-preserve-height-value=true
            data-turbo-frame-min-height-value=50
          >
            <%= render partial: 'comments/show_replies', locals: { comment_id: comment.id } %>
          </turbo-frame>
        <% else %>
          <div id="comment_<%= comment.id %>_replies_next_page"></div>
        <% end %>
      </div>
    <% end %>
  </div>
</turbo-frame>

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
    <div class="comment-wrapper ps-0 mb-3">
        <%= render comment %>
    </div>
<% end %>

<% if comments.next_page %>
    <turbo-frame
        data-controller="lazy-loader"
        id="comments_next_page"
    >
        <%= link_to '', post_comments_path(post_id: post_id,
                                           page: comments.next_page,
                                           order: order,),
                    class: 'd-none',
                    data: { 'lazy-loader-target' => 'link' }
        %>
        <div class="text-center">
            <div class="spinner-border text-danger text-center" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </turbo-frame>
<% end %>
  

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |form| %>
  <div class="d-flex">
    <% unless turbo_frame_request? %>
      <div class="author-avatar me-2">
        <%= avatar comment.user, class_name: 'img-sm rounded-circle' %>
      </div>
    <% end %>
    <div data-controller="textarea-auto-resize" class="w-100">
      <%= form.textarea :body,
        placeholder: "Share your thoughts...",
        class: "form-control border-0 rounded-4",
        data: { textarea_auto_resize_target: "textarea",
                action: "input->textarea-auto-resize#resize", },
        rows: 2
      %>
    </div>
  </div>

  <div>
    <%= form.hidden_field :user_id %>
  </div>

  <div>
    <%= form.hidden_field :post_id %>
  </div>

  <div>
    <%= form.hidden_field :replied_to_id %>
  </div>

  <div class="mt-3 d-flex justify-content-end">
    <% if turbo_frame_request? && (action_name == 'edit' || action_name == 'update') %>
      <%= link_to 'Back', comment_path(comment),
        class: "btn btn-secondary rounded-pill px-3 me-2"
      %>
    <% elsif turbo_frame_request? && (action_name == 'new' || action_name == 'create') %>
      <%= button_tag "Cancel", class: "btn btn-secondary rounded-pill px-3 me-2",
                               data: { action: 'click->turbo-frame#clearFrame' }
      %>
    <% else %>
      <%= button_tag "Cancel", class: "btn btn-secondary rounded-pill px-3 me-2", type: 'reset' %>
    <% end %>
    <%= form.submit(action_name == 'edit' || action_name == 'update' ? 'Edit' : 'Comment',
      class: "btn btn-danger rounded-pill px-3 fw-medium")
    %>
  </div>
<% end %>

app/views/comments/_new_reply.html.erb
<turbo-frame id="<%= frame_id %>"
    data-controller="turbo-frame"
    data-turbo-frame-target='content'
    data-turbo-frame-min-height-value=100
    data-turbo-frame-preserve-height-value=true
>
</turbo-frame>

app/views/comments/_show_replies.html.erb
<div id="comment_<%= comment_id %>_replies_next_page">
</div>
<%= link_to comment_replies_path(comment_id: comment_id),
            class: 'text-danger fw-medium nav-link' do
%>
    <i class="bi bi-chevron-down me-1"></i>
    <span>Show replies</span>
<% end %>

app/views/comments/_sort_button.html.erb
<div class="sort-button text-end mb-4 pe-3">
    <%= button_tag 'Sort by',
        type: 'button', class: "nav-link d-inline-block navbar-toggler rounded-pill",
        data: { bs_toggle: 'dropdown' }, aria_expanded: 'false' do
    %>
        <i class="bi bi-filter-left me-1 fs-5"></i>
        Sort by
    <% end %>
    <div class="dropdown">
        <ul class="dropdown-menu">
        <li>
            <%= link_to 'Best', post_comments_path(post_id: post_id, order: 'rating'),
                    class: 'dropdown-item', data: { turbo_frame: "post_#{post_id}_comments_frame" }
            %>
        </li>
        <li>
            <%= link_to 'Newest', post_comments_path(post_id: post_id, order: 'newer'),
                    class: 'dropdown-item', data: { turbo_frame: "post_#{post_id}_comments_frame" }
            %>
        </li>
        <li>
            <%= link_to 'Oldest', post_comments_path(post_id: post_id, order: 'older'),
                    class: 'dropdown-item', data: { turbo_frame: "post_#{post_id}_comments_frame" }
            %>
        </li>
        </ul>
    </div>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend :alerts do %>
    <%= render "shared/flash", message: notice, is_success: true %>
<% end %>

<%= turbo_stream.before "comment_#{replied_to_id}_replies_next_page" do %>
    <div class="mt-1">
        <%= render "comment", comment: @comment %>
    </div>
<% end %>

<%= turbo_stream.replace form_frame_id do %>
    <%= render partial: "comments/new_reply", locals: { frame_id: form_frame_id } %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.prepend :alerts do %>
    <%= render "shared/flash", message: notice, is_success: true %>
<% end %>

<%= turbo_stream.replace frame_id do %>
    <%= render "shared/empty_frame", frame_id: frame_id %>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h4 class="mb-3">Editing comment</h4>

<turbo-frame id="<%= dom_id @comment %>_frame">
    <div class="bg-light p-3 rounded-5">
        <%= render "form", comment: @comment, post: @post %>
    </div>
<turbo-frame>

app/views/comments/index.html.erb
<turbo-frame id="post_<%= @post_id %>_comments_frame">
    <% if @comments.any? %>
        <% unless @comments.prev_page %>
            <%= render 'sort_button', post_id: @post_id %>
        <% end %>
        <div data-turbo-frame-target='spinner' data-testid="comments">
            <%= render 'comments', comments: @comments, post_id: @post_id, order: @order %>
        </div>
    <% elsif @comments.first_page? %>
        <div class="text-secondary">
            No comments on the post yet. Be the first
        </div>
    <% end %>
</turbo-frame>

app/views/comments/index.turbo_stream.erb
<%= turbo_stream.replace 'comments_next_page' do %>
    <%= render 'comments', formats: [:html], comments: @comments, post_id: @post_id, order: @order %>
<% end %>

app/views/comments/new.html.erb
<turbo-frame id="comment_<%= @ref_reply_id || @comment.replied_to_id %>_new_reply_frame">
    <div class="new-reply pt-1 pb-3 ms-4">
        <div class="border rounded-5 bg-light p-3">
            <%= render "form", comment: @comment, post: @comment.post %>
        </div>
    </div>
<turbo-frame>

app/views/comments/show.html.erb
<%= render @comment %>

app/views/comments/update.turbo_stream.erb
<% if notice%>
    <%= turbo_stream.prepend :alerts do %>
        <%= render "shared/flash", message: notice, is_success: true %>
    <% end %>
<% end %>

<%= turbo_stream.replace frame_id do %>
    <%= render partial: "comments/comment", formats: [:html], locals: { comment: @comment } %>
<% end %>