config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }\

  get "users/:id", to: "users#show", constraints: { id: /\d+/ }, as: "user"
  get "users/:nickname", to: "users#show", constraints: { nickname: /\w+/ }, as: "nickname"
  resources :users, only: [ :edit, :update ] do
    member do
      delete :remove_avatar

      post :follow, to: "subscriptions#create"
      delete :unfollow, to: "subscriptions#destroy"
    end

    collection do
      get "profile/new", action: :new_profile, as: "new_profile"
      post "profile/create", action: :create_profile, as: "create_profile"
    end
  end

  resources :posts, except: [ :index ]  do
    post :like, to: "likes#create", as: :like
    delete :like, to: "likes#destroy", as: :unlike

    resources :comments, shallow: true do
      post :like, to: "likes#create", as: :like
      delete :like, to: "likes#destroy", as: :unlike
      get :replies
    end
  end
  get "/:feed", to: "posts#feed", as: :feed, constraints: { feed: /(hot|new|subscriptions|best)/ }

  root to: redirect("/hot")

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  MINIMUM_AGE = 14

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :posts, foreign_key: "author_id"
  has_many :comments

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :likable, source_type: "Post"
  has_many :liked_comments, through: :likes, source: :likable, source_type: "Comment"

  has_many :passive_subscriptions, class_name: "Subscription", foreign_key: :following_id, dependent: :destroy
  has_many :active_subscriptions, class_name: "Subscription", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_subscriptions, source: :follower
  has_many :followings, through: :active_subscriptions, source: :following

  has_one_attached :avatar

  enum :role, [ :user, :moderator, :editor, :admin ]

  validates :nickname,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 30 },
    format: {
      with: /\A[A-z]\w+\z/,
      message: "should start with a letter and contain only letters, numbers or underscore (_)"
    }
  validates :first_name,
    presence: true,
    length: { minimum: 3, maximum: 30 },
    format: {
      with: /\A[A-Za-z][A-Za-z\s\-]+\z/,
      message: "can only contain letters, spaces, or hyphens"
    },
    on: :update
  validates :last_name,
    presence: true,
    length: { minimum: 3, maximum: 30 },
    format: {
      with: /\A[A-Za-z][A-Za-z\s\-]+\z/,
      message: "can only contain letters, spaces, or hyphens"
    },
    on: :update
  validates :date_of_birth, presence: true, on: :update
  validates :signed_up_at, presence: true, on: :update
  validates :country,
    presence: true,
    length: { is: 2 },
    inclusion: { in: ISO3166::Country.all.map(&:alpha2), message: "is not a valid country" },
    on: :update
  validates :visible, inclusion: { in: [ true, false ], message: "can be either visible or not" }

  validate :must_be_at_least_14_years_old, on: :update

  before_create :set_registration_date
  before_create :set_false_visible

  paginates_per 50

  def thumbnail(size)
    avatar.variant(resize_to_fill: [ size, size ])
  end

  def follow!(following_user)
    Subscription.create(follower: self, following: following_user)
  end

  def unfollow!(following_user)
    Subscription.find_by(follower: self, following: following_user)&.destroy
  end

  def followed_to?(following_user)
    Subscription.exists?(follower: self, following: following_user)
  end

  def like!(likable)
    Like.create(user: self, likable: likable)
  end

  def unlike!(likable)
    Like.find_by(user: self, likable: likable)&.destroy
  end

  private

  def must_be_at_least_14_years_old
    minimum_birth_date = MINIMUM_AGE.years.ago.to_date

    if date_of_birth && date_of_birth > minimum_birth_date
      errors.add(:date_of_birth, "must be at least 14 years old")
    end
  end

  def set_registration_date
    self.signed_up_at = Time.now
  end

  def set_false_visible
    self.visible = false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [ :create ]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :nickname ])
  end

  def after_sign_up_path_for(resource)
    if resource.is_a?(User)
      new_profile_users_path
    else
      super
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_and_authorize_user, except: [ :new_profile, :create_profile ]

  def show
    @posts = @user.posts.order(published_at: :desc).includes(user: :avatar_attachment).page(params[:p])

    if user_signed_in?
      @posts = @posts.includes(preview_likes: [ user: [ :avatar_attachment ] ])
    end

    @country_name = ISO3166::Country.find_country_by_alpha2(@user.country).common_name
  end

  def edit
    @previous_page = @user
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_avatar
    @user.avatar.purge
    redirect_to :edit_user, notice: "Avatar was successfully removed."
  end

  def new_profile
    authorize User

    set_countries
  end

  def create_profile
    authorize User

    respond_to do |format|
      if current_user.update(new_profile_params.merge(visible: true))
        format.html { redirect_to current_user, notice: "Profile was successfully created." }
        format.json { render json: {}, status: :ok }
      else
        set_countries
        format.html { render :new_profile, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_countries
    @countries = ISO3166::Country.all
      .map { |country| [ country.common_name, country.alpha2 ] }
      .sort_by(&:first)
  end

  def set_and_authorize_user
    if params[:nickname]
      @user = User.find_by(nickname: params[:nickname])
    else
      @user = User.find(params.expect(:id))
    end
    authorize @user
  end

  def user_params
    params.expect(user: [ :nickname, :avatar ])
  end

  def new_profile_params
    params.expect(user: [ :first_name, :last_name, :country, :date_of_birth ])
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def avatar(user = @user, class_name: "img-md")
        size = case class_name
        when /img-md/
                200
        when /img-lg/
                300
        when /img-sm/
                100
        when /img-xs/
                25
        end
        image = user.avatar.attached? ? user.thumbnail(size) : "no-image.png"
        image_tag image, class: class_name
    end

    def nickname(user)
        "@" + user.nickname
    end

    def full_name
        "#{@user.first_name} #{@user.last_name}"
    end

    def flag
        flag_url = "https://flagcdn.com/w20/#{@user.country.downcase}.png"
        image_tag flag_url, alt: @country_name, class: "border"
    end
end

app/views/users/_follow_button.html.erb
<% if !user_signed_in? %>
    <%= button_tag 'Follow',
        class: 'btn btn-danger rounded-pill',
        data: { bs_toggle: "modal",
                bs_target: "#loginModal" } do
    %>
        <%= link_to new_user_session_path,
            class: "nav-link",
            data: {
                turbo_frame: "login_modal_frame"
            }
        %>
    <% end %>
<% elsif current_user == user %>
    <>
<% elsif !current_user.visible? %>
    <%= button_tag 'Follow', class: 'btn btn-danger rounded-pill' do %>
        <%= link_to new_profile_users_path, class: "nav-link" %>
    <% end %>
<% elsif current_user.followed_to?(user) %>
    <%= button_to 'Unfollow', unfollow_user_path(user), 
        method: :delete,
        form_class: 'd-inline-block',
        class: 'btn btn-outline-danger rounded-pill'
    %>
<% else %>
    <%= button_to 'Follow', follow_user_path(user),
        method: :post,
        form_class: 'd-inline-block',
        class: 'btn btn-danger rounded-pill'
    %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div class="mb-2 w-50">
    <%= form.label :nickname, class: "form-label" %>
    <%= form.text_field :nickname, class: "form-control" %>
  </div>

  <div class="mb-2 w-50">
    <%= form.label :avatar, 'Upload avatar', class: "form-label" %>
    <%= form.file_field :avatar, class: "form-control" %>
  </div>

  <div class="mb-4">
    <div class="border" style="min-height: 100px; width: 100px">
      <%= avatar user, class_name: 'img-sm' %>
    </div>
    <div class="mt-2">
      <% if @user.avatar.attached? %>
        <%= link_to 'Delete avatar', remove_avatar_user_path(@user),
          data: { confirm: "Are you sure?", turbo_method: :delete },
          class: 'btn btn-outline-secondary'
        %>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <div class='row'>
    <div class='col-12 col-lg-4 col-xxl-3 mb-4 mb-lg-0 d-flex align-items-center'>
      <div class="profile-avatar d-inline-block position-relative overflow-hidden rounded-circle">
        <%= avatar class_name: 'img-md rounded-circle img-thumbnail' %>
        <% if user == current_user %>
          <div class="bg-dark change-avatar position-absolute top-0 w-100 h-100 fs-1 d-flex 
                      align-items-center justify-content-center text-white"
               data-bs-toggle="modal" data-bs-target="#imageModal"
          >
            <i class="bi bi-camera"></i>
          </div>
        <% end %>
      </div>
    </div>
    <div class='col-12 col-lg-8 col-xxl-9 ps-3'>
      <div class="mb-3 d-flex justify-content-between">
        <div class="d-inline-block">
          <h4 class="fw-bold mb-1">
            <%= full_name %>
          </h4>
          <div class="text-secondary">
            <%= nickname(user) %>
          </div>
        </div>
        <div>
          <%= render 'shared/follow_button', user: user, small: false %>
          <% if @user == current_user && @user.visible? %>
              <%= link_to edit_user_path(@user), class: "btn btn-outline-danger rounded-pill" do %>
                <i class="bi bi-pencil me-1"></i>
                <span>Edit profile</span>
              <% end %>
          <% end %>
        </div>
      </div>

      <div class="text-secondary">
        <% if user.visible? %>        
          <div class="mb-2">
            <div class="country-flag d-inline me-1">
              <%= flag %>
            </div>
            <%= @country_name %>
          </div>
          <div>
            Joined <%= days_ago_in_words user.signed_up_at %>
          </div>
          <div class="d-block mt-2">
            Rating :
            <span class="text-danger">
              <i class="bi bi-person-arms-up"></i>
              <span class='user-rating fw-bold'>
                <%= user.rating %>
              </span>
            </span>
          </div>
        <% elsif current_user == user %>
          <div class="bg-light rounded-4 border border-3 px-5 py-3 text-center">
            <h6 class="fw-normal">Please fill your personal details to use all the Poster's features</h6>
            <div class="my-2 fs-4 text-secondary">
              <i class="bi bi-arrow-down"></i>
            </div>
            <%= link_to 'Create profile', new_profile_users_path, class: 'btn btn-danger' %>
          </div>
        <% else %>
          <div class="bg-light rounded-4 border border-3 p-5 text-center">
            <h6 class="fw-normal">The user has not been completed information about himself</h6>
          </div>
        <% end %>
      </div>

      <div class="mt-3 d-flex text-secondary">
        <div class="pe-4 border-end">
          Followers :
          <span class="text-danger fw-semibold fs-5 ms-2"><%= user.followers_count%></span>
        </div>
        <div class="ps-4 pe-4">
          Followings :
          <span class="text-danger fw-semibold fs-5 ms-2"><%= user.followings_count %></span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Edit profile" %>

<h2>Edit profile</h2>

<%= render "form", user: @user %>

app/views/users/new_profile.html.erb
<% content_for :title, "Create profile" %>

<h2>Create profile</h2>

<%= form_with model: current_user, url: create_profile_users_path, method: :post do |form| %>
    <div class="mb-3">
        <%= form.label :first_name, class: 'form-label' %>
        <%= form.text_field :first_name, value: '', class: 'form-control' %>
    </div>

    <div class="mb-3">
        <%= form.label :last_name, class: 'form-label' %>
        <%= form.text_field :last_name, value: '', class: 'form-control' %>
    </div>

    <div class="mb-3">
        <%= form.label :date_of_birth, class: 'form-label' %>
        <%= form.date_field :date_of_birth, value: Date.today, class: 'form-control' %>
    </div>

    <div class="mb-3">
        <%= form.label :country, class: 'form-label' %>
        <%= form.select(:country, options_for_select(@countries, selected: 'US'), { }, { class: 'form-select' }) %>
    </div>

    <div class="mt-3">
        <%= form.submit 'Save', class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/users/show.html.erb
<% content_for :title, @user.nickname %>

<%= render @user %>

<% if @user == current_user %>
  <div class="modal fade" id="imageModal" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content p-5">
        <div class=''>
          <%= form_with(model: @user) do |form| %>
            <div class="mb-2">
              <%= form.file_field :avatar, class: "form-control" %>
            </div>
            <div class="controls mt-4 text-center">
              <div class="">
                <% if @user.avatar.attached? %>
                  <%= link_to 'Delete current avatar', remove_avatar_user_path(@user),
                    data: { confirm: "Are you sure?", turbo_method: :delete },
                    class: 'btn btn-outline-secondary'
                  %>
                <% end %>
                <%= form.submit 'Upload new avatar', class: "btn btn-danger" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<hr class="mt-5 mb-4"/>

<div id='user-posts'>
  <% if @posts.any? %>
    <h4 class="ms-3 mb-3">All posts</h4>
    <%= render 'posts/posts', posts: @posts, filter: { feed: 'new', user_id: @user.id } %>
  <% else %>
      <% if @user == current_user %>
        <div class="text-secondary mb-3">
          You don't have any posts yet. Write your first!
        </div>
        <%= link_to 'New post', new_post_path, class: 'btn btn-secondary px-4 rounded-pill' %>
      <% else %>
        <div class="text-secondary">
          User does not have any posts
        </div>
      <% end %>
    </div>
  <%- end %>
</div>