config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }\

  get "users/:id", to: "users#show", constraints: { id: /\d+/ }, as: "user"
  get "users/:nickname", to: "users#show", constraints: { nickname: /\w+/ }, as: "nickname"
  resources :users, only: [ :edit, :update ] do
    member do
      delete :remove_avatar

      post :follow, to: "subscriptions#create"
      delete :unfollow, to: "subscriptions#destroy"
    end

    collection do
      get "profile/new", action: :new_profile, as: "new_profile"
      post "profile/create", action: :create_profile, as: "create_profile"
    end
  end

  resources :posts, except: [ :index ]  do
    post :like, to: "likes#create", as: :like
    delete :like, to: "likes#destroy", as: :unlike

    resources :comments, shallow: true do
      post :like, to: "likes#create", as: :like
      delete :like, to: "likes#destroy", as: :unlike
      get :replies
    end
  end
  get "/:feed", to: "posts#feed", as: :feed, constraints: { feed: /(hot|new|subscriptions|best)/ }

  root to: redirect("/hot")

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_empty_frame.html.erb
<turbo-frame id="<%= frame_id %>"></turbo-frame>

app/views/shared/_flash.html.erb
<%= content_tag :div,
                class: "alert alert-#{is_success ? 'success' : 'danger'} text-center"\
                       " d-flex align-items-center mt-3 rounded-pill",
                role: 'alert',
                data: { controller: "alert" } do
%>
    <%= content_tag :i, '', class: "bi bi-#{is_success ? 'check-circle-fill' : 'exclamation-triangle-fill'} me-3" %>
    <p class="mb-0"><%= message.strip.gsub(/\n/, '<br/>').html_safe %></p>
    <button type="button" class="btn-close ms-2" data-bs-dismiss="alert" aria-label="Close"></button>
<% end %>

app/views/shared/_follow_button.html.erb
<% if !user_signed_in? %>
    <%= button_tag class: "btn btn-danger rounded-pill py-1 px-3 fw-semibold",
                   data: { bs_toggle: "modal",
                           bs_target: "#loginModal" } do
    %>
        <%= link_to 'Follow', new_user_session_path,
            class: "nav-link",
            data: {
                turbo_frame: "login_modal_frame"
            }
        %>
    <% end %>
<% elsif current_user == user %>
<% elsif !current_user.visible? %>
    <%= button_tag class: "btn btn-danger rounded-pill py-1 px-3 fw-semibold" do %>
        <%= link_to 'Follow', new_profile_users_path, class: "nav-link" %>
    <% end %>
<% elsif current_user.followed_to?(user) %>
    <%= button_to 'Unfollow', unfollow_user_path(user), 
        method: :delete,
        form_class: 'd-inline-block',
        class: "btn btn-outline-danger rounded-pill py-1 px-3 fw-semibold"
    %>
<% else %>
    <%= button_to 'Follow', follow_user_path(user),
        method: :post,
        form_class: 'd-inline-block',
        class: "btn btn-danger rounded-pill py-1 px-3 fw-semibold"
    %>
<% end %>

app/views/shared/_like.html.erb
<% if current_user&.visible? %>
    <div class="position-relative">
        <%= button_tag class: "nav-link like",
            data: { controller: "likes",
                    action: 'click->likes#like',
                    likes_is_liked_value: resource.liked?(current_user),
                    likes_resource_id_value: resource.id,
                    likes_collection_name_value: resource.model_name.collection,
                    likes_is_authorized_value: user_signed_in?, } do
        %>
            <div class="like-inner text-danger">
                <%= tag.i(
                    class: "bi bi-heart me-1 align-text-top d-inline-block",
                    data: { likes_target: 'likeButton' }
                )%>
                <span data-likes-target='likeCount'>
                    <%= resource.likes_count %>
                </span>
            </div>
        <% end %>
        <div class="likes-preview position-absolute bottom-100 start-0 d-flex p-2 rounded-5">
            <% (@preview_likes || resource.preview_likes).each do |preview_like| %>
                <%= link_to preview_like.user, class: 'd-flex mx-1' do %>
                    <%= avatar preview_like.user, class_name: 'img-xs rounded-circle' %>
                <% end %>
            <% end %>
        </div>
    </div>
<% elsif user_signed_in? %>
    <%= button_tag class: 'nav-link like' do %>
        <%= link_to new_profile_users_path,
            class: "nav-link" do
        %>
            <div class="like-inner text-danger">
                <%= tag.i(
                    class: "bi bi-heart me-1 align-text-top d-inline-block",
                    data: { 'likes-target': 'likeButton' }
                )%>
                <span data-likes-target='likeCount'>
                    <%= resource.likes_count %>
                </span>
            </div>
        <% end %>
    <% end %>
<% else %>
    <%= button_tag class: 'nav-link like',
        data: { bs_toggle: "modal",
                bs_target: "#loginModal" } do
    %>
        <%= link_to new_user_session_path,
            class: "nav-link",
            data: {
                turbo_frame: "login_modal_frame"
            } do
        %>
            <div class="like-inner text-danger">
                <i class="bi bi-heart me-1 align-text-top d-inline-block"></i>
                <span>
                    <%= resource.likes_count %>
                </span>
            </div>
        <% end %>
    <% end %>
<% end %>