config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }\

  get "users/:id", to: "users#show", constraints: { id: /\d+/ }, as: "user"
  get "users/:nickname", to: "users#show", constraints: { nickname: /\w+/ }, as: "nickname"
  resources :users, only: [ :edit, :update ] do
    member do
      delete :remove_avatar

      post :follow, to: "subscriptions#create"
      delete :unfollow, to: "subscriptions#destroy"
    end

    collection do
      get "profile/new", action: :new_profile, as: "new_profile"
      post "profile/create", action: :create_profile, as: "create_profile"
    end
  end

  resources :posts, except: [ :index ]  do
    post :like, to: "likes#create", as: :like
    delete :like, to: "likes#destroy", as: :unlike

    resources :comments, shallow: true do
      post :like, to: "likes#create", as: :like
      delete :like, to: "likes#destroy", as: :unlike
      get :replies
    end
  end
  get "/:feed", to: "posts#feed", as: :feed, constraints: { feed: /(hot|new|subscriptions|best)/ }

  root to: redirect("/hot")

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
    include Likable

    belongs_to :user, foreign_key: :author_id
    has_many :comments, dependent: :destroy

    validates :title, length: { minimum: 5, maximum: 50 }
    validates :body, length: { minimum: 15, maximum: 1000 }

    before_save :generate_random_seed

    scope :random, ->(seed) { order(Arel.sql("ABS(random_seed - #{seed.to_f})")) }
    scope :from_user, ->(user_id) { where(author_id: user_id) }
    scope :fresh, ->() { order(published_at: :desc) }
    scope :best, ->() { order(likes_count: :desc) }
    scope :subscriptions, ->(user) { where(author_id: user.followings) }

    paginates_per 10

    def publish!
        raise "Post is already published" if published?

        self.published_at = DateTime.now
    end

    def published?
        self.published_at.present?
    end

    private

    def generate_random_seed
        self.random_seed = rand
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_and_authorize_post, only: %i[ show edit update destroy ]

  def feed
    @filter = { feed: params[:feed] }

    if params[:user_id]
      user = User.find(params[:user_id])
      return head :not_found unless user

      @filter = { user_id: params[:user_id] }
      @posts = Post.from_user(user).fresh
    elsif params[:feed] == "hot"
      @filter.merge!(seed_id: params[:seed_id] || rand.round(5))
      @posts = Post.random(@filter[:seed_id])
    elsif params[:feed] == "new"
      @posts = Post.fresh
    elsif params[:feed] == "best"
      @posts = Post.best
    elsif params[:feed] == "subscriptions"
      @posts = Post.subscriptions(current_user).fresh
    end

    @posts = @posts.with_user_like(current_user)
                   .includes(user: :avatar_attachment)
                   .page(params[:page])

    if user_signed_in?
      @posts = @posts.includes(preview_likes: [ user: [ :avatar_attachment ] ])
    end

    render :feed, formats: turbo_frame_request? ? :turbo_stream : :html
  end

  def show
    @new_comment = Comment.new(post: @post, user: current_user)
    @comments_order = params[:corder] || "rating"
    @preview_likes = @post.preview_likes.includes(user: [ :avatar_attachment ])
  end

  def new
    @post = Post.new
    authorize @post
  end

  def edit
    @previous_page = @post
  end

  def create
    @post = Post.new(post_params)
    authorize @post
    @post.user = current_user
    @post.publish!

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        @previous_page = @post
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to @post.user, status: :see_other, notice: "Post was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_and_authorize_post
    @post = Post.find(params.expect(:id))
    authorize @post
  end

  def post_params
    params.expect(post: [ :title, :body ])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
    def format_post_date(date)
        date.in_time_zone("Warsaw").to_date.inspect
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div>
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :body, class: "form-label" %>
    <%= form.textarea :body, class: 'form-control', style: 'min-height: 500px' %>
  </div>

  <div class="mt-3">
    <%= form.submit 'Post', class: 'btn btn-danger px-5' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="px-4 py-3 bg-light rounded-4 ps-lg-5">
  <div class="row mb-2">
    <div class="d-flex align-items-center">
      <div class="post-avatar me-2 d-inline-block">
        <%= avatar post.user, class_name: 'img-xs rounded-circle' %>
      </div>
      <%= link_to nickname(post.user), post.user, class: "nav-link text-danger fw-medium" %>
      <span class="text-secondary mx-2">
        •
      </span>
      <div class="d-inline text-secondary" title="<%= post.published_at %>" role="button">
        <%= time_ago_in_words post.published_at.to_i %> ago
      </div>
    </div>
  </div>

  <div class="post-heading mb-3">
    <h3>
      <%= link_to post.title, post, class: "nav-link" %>
    </h3>
  </div>

  <div data-controller='read-more' data-read-more-max-height-value=300>
    <div class="post-content" data-read-more-target="textToHide">
      <%= simple_format post.body %>
    </div>
    <div class="position-relative" data-read-more-target="showMoreButton" hidden>
      <div class="post-show-more-fade position-absolute w-100 bottom-100"></div>
      <button class="show-more-btn nav-link text-danger"
              data-action='click->read-more#showMore'>
        Show more ...
      </button>
    </div>
  </div>

  <div class="post-footer text-secondary mt-3 d-flex align-items-center">
    <div class="d-inline-block me-4">
      <%= render 'shared/like', resource: post %>
    </div>
    <%= link_to post_path(post), class: 'nav-link d-inline' do %>
      <i class="bi bi-chat-fill me-1"></i>
      <%= post.comments_count %>
    <% end %>
  </div>
</div>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
    <div class="post-wrapper ps-0 mb-3">
        <%= render post %>
    </div>
<% end %>

<% if posts.next_page %>
    <turbo-frame
        id="posts_next_page"
        data-controller="lazy-loader"
    >
        <%= link_to '', feed_path(filter.merge(page: posts.next_page)),
                    class: 'd-none',
                    data: { 'lazy-loader-target' => 'link', testid: 'next_page_link' }
        %>
        <div class="text-center">
            <div class="spinner-border text-danger text-center" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </turbo-frame>
<% end %>

app/views/posts/edit.html.erb
<% content_for :title, "Edit post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

app/views/posts/feed.html.erb
<div id="feed">
  <% if @posts.any? %>
    <%= render 'posts', posts: @posts, filter: @filter %>
  <% else %>
    <div class="text-center my-5">
      <h4>No posts available</h4>
      <p class="text-body-secondary">Try adjusting your filters or check back later.</p>
    </div>
  <% end %>
</div>

app/views/posts/feed.turbo_stream.erb
<%= turbo_stream.replace 'posts_next_page' do %>
    <%= render 'posts', formats: [:html], posts: @posts, filter: @filter %>
<% end %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>

<div class="bg-light px-3 py-2 rounded-pill d-inline-block">
  <div class="d-flex align-items-center">
    <div class="post-avatar me-2 d-inline-block">
      <%= avatar @post.user, class_name: 'img-xs rounded-circle' %>
    </div>
    <%= link_to nickname(@post.user), @post.user, class: "nav-link text-danger fw-medium" %>
    <span class="text-secondary mx-2">
      • 
    </span>
    <div class="d-inline text-secondary" title="<%= @post.published_at %>" role="button">
      <%= time_ago_in_words @post.published_at%> ago
    </div>
  </div>
</div>

<h1 class="ps-3 mb-4 mt-3 border-start border-danger border-opacity-50 border-3">
  <%= @post.title %>
</h1>

<div class="mb-3 post-content px-3">
  <%= simple_format @post.body %>
</div>

<div class="fs-5 rounded-pill text-secondary d-inline-block px-3 py-1 bg-light">
  <div class="d-inline-block me-4">
    <%= render 'shared/like', resource: @post %>
  </div>
  <%= link_to post_path(@post, anchor: 'comments'), class: 'nav-link d-inline-block', data: { testid: 'comments_count' } do %>
    <i class="bi bi-chat-fill me-1"></i>
    <%= @post.comments_count %>
  <% end %>
</div>
 
<%- if current_user == @post.user %>
  <div class="my-3">
    <div class="d-inline">
      <%= link_to "Edit post", edit_post_path(@post), class: 'btn btn-outline-secondary' %>
    </div>
    <%= button_to "Delete post", @post, method: :delete, class: 'btn btn-outline-danger', form_class: 'd-inline' %>
  </div>
<%- end %>

<div id="comments" class="mt-4">
  <div class='mb-4 bg-light p-3 border rounded-5'>
    <% if user_signed_in? %>
      <div data-testid="new_comment_form">
        <%= render "comments/form", post: @post, comment: @new_comment %>
      </div>
    <% else %>
      <div class="text-center text-secondary my-2">
        <span>
          You need to
          <span class="d-inline" data-bs-toggle="modal" data-bs-target="#loginModal">
            <%= link_to "sign in", new_user_session_path,
                  class: 'link-underline link-underline-opacity-0',
                  data: { turbo_frame: "login_modal_frame" }
            %>
          </span>
          to leave a comment
        </span>
      </div>
    <% end %>
  </div>

  <div id='comments-list' class="">
    <turbo-frame
      id="post_<%= @post.id %>_comments_frame"
      src="<%= post_comments_path(post_id: @post.id, order: @comments_order) %>"
      data-controller="turbo-frame"
    >
      <div class='d-flex justify-content-center'>
        <div class="spinner-border text-danger" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    <turbo-frame>
  </div>
</div>